var hierarchy =
[
    [ "AbstractPostEffectFactory", "classAbstractPostEffectFactory.html", null ],
    [ "AbstractSceneFactory", "classAbstractSceneFactory.html", null ],
    [ "Animation", "structAnimation.html", null ],
    [ "AnimationCurve< T >", "structAnimationCurve.html", null ],
    [ "AnimationCurve< Quaternion >", "structAnimationCurve.html", null ],
    [ "AnimationCurve< Vector3 >", "structAnimationCurve.html", null ],
    [ "Ui::AnimSlot", "structUi_1_1AnimSlot.html", null ],
    [ "Camera", "classCamera.html", null ],
    [ "CameraController", "classCameraController.html", null ],
    [ "CameraDirector", "classCameraDirector.html", null ],
    [ "CameraForGpu", "structCameraForGpu.html", null ],
    [ "CameraRepository", "classCameraRepository.html", null ],
    [ "Ui::Canvas", "classUi_1_1Canvas.html", null ],
    [ "CollisionManager", "classCollisionManager.html", null ],
    [ "Common", "classCommon.html", [
      [ "LineCommon", "classLineCommon.html", null ],
      [ "ModelCommon", "classModelCommon.html", null ],
      [ "SkyCommon", "classSkyCommon.html", null ],
      [ "SpriteCommon", "classSpriteCommon.html", null ],
      [ "TextCommon", "classTextCommon.html", null ]
    ] ],
    [ "ComputePipeline", "classComputePipeline.html", null ],
    [ "GameEngine::Config", "structGameEngine_1_1Config.html", null ],
    [ "GameEngine::ConfigLoader", "classGameEngine_1_1ConfigLoader.html", null ],
    [ "SceneSwitcher::Context", "structSceneSwitcher_1_1Context.html", null ],
    [ "D3DResourceLeakChecker", "classD3DResourceLeakChecker.html", null ],
    [ "Ui::SpriteElement::Data", "structUi_1_1SpriteElement_1_1Data.html", null ],
    [ "Ui::TextElement::Data", "structUi_1_1TextElement_1_1Data.html", null ],
    [ "DebugUI", "classDebugUI.html", null ],
    [ "DirectionalLight", "structDirectionalLight.html", null ],
    [ "DirectXAdapter", "classDirectXAdapter.html", null ],
    [ "DX12Resource", "classDX12Resource.html", null ],
    [ "Ui::Element", "classUi_1_1Element.html", [
      [ "Ui::SpriteElement", "classUi_1_1SpriteElement.html", null ],
      [ "Ui::TextElement", "classUi_1_1TextElement.html", null ]
    ] ],
    [ "Ui::Canvas::ElementRect", "structUi_1_1Canvas_1_1ElementRect.html", null ],
    [ "Emitter", "classEmitter.html", null ],
    [ "ParticleSystem::EmitterConfig", "structParticleSystem_1_1EmitterConfig.html", null ],
    [ "Ui::Manager::Entry", "structUi_1_1Manager_1_1Entry.html", null ],
    [ "Ui::EventSystem", "classUi_1_1EventSystem.html", null ],
    [ "FrameDebugger", "classFrameDebugger.html", null ],
    [ "FrameRateLimiter", "classFrameRateLimiter.html", null ],
    [ "Framework", "classFramework.html", null ],
    [ "std::hash< Ui::EventKey >", "structstd_1_1hash_3_01Ui_1_1EventKey_01_4.html", null ],
    [ "Heap", "classHeap.html", null ],
    [ "IGame", "classIGame.html", null ],
    [ "IModelLoader", "classIModelLoader.html", [
      [ "GltfLoader", "classGltfLoader.html", null ],
      [ "ObjLoader", "classObjLoader.html", null ]
    ] ],
    [ "Input", "classInput.html", null ],
    [ "InputLayout", "classInputLayout.html", null ],
    [ "IPostEffect", "classIPostEffect.html", [
      [ "BoxBlur", "classBoxBlur.html", null ],
      [ "Grayscale", "classGrayscale.html", null ],
      [ "Vignette", "classVignette.html", null ]
    ] ],
    [ "IScene", "classIScene.html", [
      [ "SampleScene", "classSampleScene.html", null ]
    ] ],
    [ "ITransitionEffect", "classITransitionEffect.html", [
      [ "Fade", "classFade.html", null ]
    ] ],
    [ "Joint", "structJoint.html", null ],
    [ "JointWeightData", "structJointWeightData.html", null ],
    [ "JsonParams", "classJsonParams.html", null ],
    [ "Keyframe< T >", "structKeyframe.html", null ],
    [ "LevelData", "structLevelData.html", null ],
    [ "LevelEditor", "classLevelEditor.html", null ],
    [ "LightManager", "classLightManager.html", null ],
    [ "Line", "classLine.html", null ],
    [ "Log", "classLog.html", null ],
    [ "Log::LogEntry", "structLog_1_1LogEntry.html", null ],
    [ "Ui::Manager", "classUi_1_1Manager.html", null ],
    [ "Material", "structMaterial.html", null ],
    [ "PostProcessExecutor::Work::Member", "structPostProcessExecutor_1_1Work_1_1Member.html", null ],
    [ "Mesh", "classMesh.html", null ],
    [ "MeshData", "structMeshData.html", null ],
    [ "MeshRepository", "classMeshRepository.html", null ],
    [ "Model", "classModel.html", null ],
    [ "ModelData", "structModelData.html", null ],
    [ "ModelRepository", "classModelRepository.html", null ],
    [ "Node", "structNode.html", null ],
    [ "NodeAnimation", "structNodeAnimation.html", null ],
    [ "LevelData::ObjectData", "structLevelData_1_1ObjectData.html", null ],
    [ "Particle", "classParticle.html", null ],
    [ "ParticleSystem", "classParticleSystem.html", null ],
    [ "PipelineStateObject", "classPipelineStateObject.html", null ],
    [ "PointLight", "structPointLight.html", null ],
    [ "PostProcessExecutor", "classPostProcessExecutor.html", null ],
    [ "PostProcessPresetEditor", "classPostProcessPresetEditor.html", null ],
    [ "PostProcessPresetEditor::PresetData", "structPostProcessPresetEditor_1_1PresetData.html", null ],
    [ "PostProcessPresetEditor::PresetMember", "structPostProcessPresetEditor_1_1PresetMember.html", null ],
    [ "RawLight", "classRawLight.html", [
      [ "RawDirectionalLight", "classRawDirectionalLight.html", null ],
      [ "RawPointLight", "classRawPointLight.html", null ],
      [ "RawSpotLight", "classRawSpotLight.html", null ]
    ] ],
    [ "Renderer", "classRenderer.html", null ],
    [ "Common::RenderingCommand", "structCommon_1_1RenderingCommand.html", null ],
    [ "ResourceRepository", "classResourceRepository.html", null ],
    [ "RootSignature", "classRootSignature.html", null ],
    [ "SceneFactory", "classSceneFactory.html", null ],
    [ "SceneSwitcher", "classSceneSwitcher.html", null ],
    [ "Scheduler", "classScheduler.html", null ],
    [ "Shader", "classShader.html", null ],
    [ "ShadowCubeMap", "classShadowCubeMap.html", null ],
    [ "ShadowPass", "classShadowPass.html", null ],
    [ "Skeleton", "structSkeleton.html", null ],
    [ "Skybox", "classSkybox.html", null ],
    [ "SpotLight", "structSpotLight.html", null ],
    [ "Sprite", "classSprite.html", null ],
    [ "SRVManager", "classSRVManager.html", null ],
    [ "StageLoader", "classStageLoader.html", null ],
    [ "StageRepository", "classStageRepository.html", null ],
    [ "ParticleSystem::Template", "structParticleSystem_1_1Template.html", null ],
    [ "ParticleSystem::TemplateEditor", "classParticleSystem_1_1TemplateEditor.html", null ],
    [ "Text", "classText.html", null ],
    [ "TextureManager", "classTextureManager.html", null ],
    [ "Timer", "classTimer.html", null ],
    [ "Transition", "classTransition.html", null ],
    [ "Vertex", "structVertex.html", null ],
    [ "VertexWeightData", "structVertexWeightData.html", null ],
    [ "WinApp", "classWinApp.html", null ],
    [ "Window", "classWindow.html", null ]
];